### ISSUE TITLE
登录的问题

### ISSUE THREAD

**Issue by lennyup** [yuche/gouqi#11]
问题一：
您这的登录是和网易云音乐上的数据一样吗 我用自己的网易云音乐 登录不上去 如果方便的话 能不能告诉我个账号和密码
问题二：
 我如何查看log信息

**Comment by yuche** [comment]
1. 一样，用手机帐号登录。
2. cmd + d 开 dev 模式在 chrome 里查看。

**Comment by lennyup** [comment]
谢谢解答
