### ISSUE TITLE
安装失败

### ISSUE THREAD

**Issue by wulucxy** [yuche/gouqi#6]
```
> gouqi@0.9.0 quickbuild /work/react/gouqi
> tsc --noUnusedParameters --noUnusedLocals

src/components/Slider.tsx(126,33): error TS6133: 'trackSize' is declared but never used.
src/components/Slider.tsx(127,9): error TS6133: 'mainStyles' is declared but never used.
src/components/Slider.tsx(138,9): error TS6133: 'minimumTrackStyle' is declared but never used.
src/components/Slider.tsx(145,9): error TS6133: 'touchOverflowStyle' is declared but never used.
src/components/Slider.tsx(213,30): error TS6133: 'e' is declared but never used.
src/components/Slider.tsx(222,33): error TS6133: 'e' is declared but never used.
src/components/Slider.tsx(222,44): error TS6133: 'gestureState' is declared but never used.
src/components/Slider.tsx(227,29): error TS6133: 'e' is declared but never used.
src/sagas/common.ts(77,21): error TS2346: Supplied parameters do not match any signature of call target.

npm ERR! Darwin 16.4.0
npm ERR! argv "/Users/qingtong/.nvm/versions/node/v7.0.0/bin/node" "/Users/qingtong/.nvm/versions/node/v7.0.0/bin/npm" "run" "quickbuild"
npm ERR! node v7.0.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! gouqi@0.9.0 quickbuild: `tsc --noUnusedParameters --noUnusedLocals`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the gouqi@0.9.0 quickbuild script 'tsc --noUnusedParameters --noUnusedLocals'.
```

**Comment by yuche** [comment]
这个不用管，对程序运行是没有影响的。`Slider` 其实是一个第三方依赖，但他的官方 repo 不维护了，所以 React Native 更新到 0.44 之后就不能用。所以源码部分的 `Slider` 实际上是 `react-native-slider` 的一个支持新版本 RN 的 mirror。考虑新建一个 repo 把它单独拿出去了。
          
            
            On 6月 12 2017, at 11:33 中午, wulu <notifications@github.com> wrote:
            
            
              > gouqi@0.9.0 quickbuild /work/react/gouqi
> tsc --noUnusedParameters --noUnusedLocals

src/components/Slider.tsx(126,33): error TS6133: 'trackSize' is declared but never used.
src/components/Slider.tsx(127,9): error TS6133: 'mainStyles' is declared but never used.
src/components/Slider.tsx(138,9): error TS6133: 'minimumTrackStyle' is declared but never used.
src/components/Slider.tsx(145,9): error TS6133: 'touchOverflowStyle' is declared but never used.
src/components/Slider.tsx(213,30): error TS6133: 'e' is declared but never used.
src/components/Slider.tsx(222,33): error TS6133: 'e' is declared but never used.
src/components/Slider.tsx(222,44): error TS6133: 'gestureState' is declared but never used.
src/components/Slider.tsx(227,29): error TS6133: 'e' is declared but never used.
src/sagas/common.ts(77,21): error TS2346: Supplied parameters do not match any signature of call target.

npm ERR! Darwin 16.4.0
npm ERR! argv "/Users/qingtong/.nvm/versions/node/v7.0.0/bin/node" "/Users/qingtong/.nvm/versions/node/v7.0.0/bin/npm" "run" "quickbuild"
npm ERR! node v7.0.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! gouqi@0.9.0 quickbuild: `tsc --noUnusedParameters --noUnusedLocals`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the gouqi@0.9.0 quickbuild script 'tsc --noUnusedParameters --noUnusedLocals'.

**Comment by yuche** [comment]
`common.ts` 实际上是目前版本 `redux-saga`的 `call` 方法 `typings` 有一点小问题，等有空了我给他们发一个 PR 解决一下。
          
            
            On 6月 12 2017, at 11:33 中午, wulu <notifications@github.com> wrote:
            
            
              > gouqi@0.9.0 quickbuild /work/react/gouqi
> tsc --noUnusedParameters --noUnusedLocals

src/components/Slider.tsx(126,33): error TS6133: 'trackSize' is declared but never used.
src/components/Slider.tsx(127,9): error TS6133: 'mainStyles' is declared but never used.
src/components/Slider.tsx(138,9): error TS6133: 'minimumTrackStyle' is declared but never used.
src/components/Slider.tsx(145,9): error TS6133: 'touchOverflowStyle' is declared but never used.
src/components/Slider.tsx(213,30): error TS6133: 'e' is declared but never used.
src/components/Slider.tsx(222,33): error TS6133: 'e' is declared but never used.
src/components/Slider.tsx(222,44): error TS6133: 'gestureState' is declared but never used.
src/components/Slider.tsx(227,29): error TS6133: 'e' is declared but never used.
src/sagas/common.ts(77,21): error TS2346: Supplied parameters do not match any signature of call target.

npm ERR! Darwin 16.4.0
npm ERR! argv "/Users/qingtong/.nvm/versions/node/v7.0.0/bin/node" "/Users/qingtong/.nvm/versions/node/v7.0.0/bin/npm" "run" "quickbuild"
npm ERR! node v7.0.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! gouqi@0.9.0 quickbuild: `tsc --noUnusedParameters --noUnusedLocals`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the gouqi@0.9.0 quickbuild script 'tsc --noUnusedParameters --noUnusedLocals'.

**Comment by yuche** [comment]
最新的 commit 解决了这个问题。
