### ISSUE TITLE
启动不了server

### ISSUE THREAD

**Issue by lionheart2016** [yuche/gouqi#7]
控制台报错。
<img width="570" alt="qq20170613-135136 2x" src="https://user-images.githubusercontent.com/20981126/27067844-827eb56c-503f-11e7-9c8c-1858023966b2.png">

**Comment by yuche** [comment]
1. `npm run link` 出现错误了吗？
2. 8081 端口是否被占用？
3. 运行 `run-ios` 时编译是否成功？

**Comment by TheWaWaR** [comment]
可以看看这里的讨论：
- https://github.com/facebook/react-native/issues/10088
- https://github.com/facebook/react-native/issues/910

**Comment by lionheart2016** [comment]
1, link 没错误
2， 端口没占用
3， 编译能成功。
4， npm run quickbuild 不行。

guangfahkdeMacBook:gouqi gfhk$ yarn run quickbuild
yarn run v0.21.3
$ tsc --noUnusedParameters --noUnusedLocals 
node_modules/@types/react/index.d.ts(165,11): error TS2559: Type 'Component<P, S>' has no properties in common with type 'ComponentLifecycle<P, S>'.
src/containers/ArtistAlbumsPage.tsx(20,3): error TS2345: Argument of type '(s: { albums: any; isLoading: any; }, d: { sync(): Action<string>; }, o: IProps) => { albums: IAl...' is not assignable to parameter of type 'MergeProps<{ albums: any; isLoading: any; }, { sync(): Action<string>; }, IProps>'.
  Type '{ albums: IAlbum[]; isLoading: boolean; sync: () => Action; id: number; tabLabel: string; }' is not assignable to type '{ albums: any; isLoading: any; } & { sync(): Action<string>; }'.
    Object literal may only specify known properties, and 'id' does not exist in type '{ albums: any; isLoading: any; } & { sync(): Action<string>; }'.
src/containers/ArtistDescription.tsx(18,3): error TS2345: Argument of type '(s: { description: any; isLoading: any; }, d: { sync(): Action<string>; }, o: IProps) => { id: nu...' is not assignable to parameter of type 'MergeProps<{ description: any; isLoading: any; }, { sync(): Action<string>; }, IProps>'.
  Type '{ id: number; name: string; tabLabel: string; sync: () => Action; isLoading: boolean; description...' is not assignable to type '{ description: any; isLoading: any; } & { sync(): Action<string>; }'.
    Object literal may only specify known properties, and 'id' does not exist in type '{ description: any; isLoading: any; } & { sync(): Action<string>; }'.
src/containers/ArtistTracksPage.tsx(14,3): error TS2345: Argument of type '(s: { tracks: any; isLoading: any; }, d: { sync(): Action<string>; }, o: IProps) => { id: number;...' is not assignable to parameter of type 'MergeProps<{ tracks: any; isLoading: any; }, { sync(): Action<string>; }, IProps>'.
  Type '{ id: number; tabLabel: string; tracks: ITrack[]; isLoading: boolean; sync: () => Action; showInd...' is not assignable to type '{ tracks: any; isLoading: any; } & { sync(): Action<string>; }'.
    Object literal may only specify known properties, and 'id' does not exist in type '{ tracks: any; isLoading: any; } & { sync(): Action<string>; }'.
src/reducers/detail.ts(26,30): error TS2345: Argument of type '{ 'details/playlist/start'(state: IinitialState): { isLoading: boolean; playlist: IPlaylists; sub...' is not assignable to parameter of type 'ReducerMap<IinitialState, {}>'.
  Property ''details/playlist/save'' is incompatible with index signature.
    Type '(state: IinitialState, { payload }: Action<{}>) => { playlist: {} | {}; subscribing: boolean; isL...' is not assignable to type 'Reducer<IinitialState, {}>'.
      Type '{ playlist: {} | {}; subscribing: boolean; isLoading: boolean; albums: IAlbums; }' is not assignable to type 'IinitialState'.
        Types of property 'playlist' are incompatible.
          Type '{} | {}' is not assignable to type 'IPlaylists'.
            Type '{}' is not assignable to type 'IPlaylists'.
              Index signature is missing in type '{}'.
src/reducers/download.ts(24,30): error TS2345: Argument of type '{ 'download/tracks/merge'(state: IDownloadState, { payload }: any): { tracks: ITrack[]; progress:...' is not assignable to parameter of type 'ReducerMap<IDownloadState, ITrack[]>'.
  Property ''download/tracks/set'' is incompatible with index signature.
    Type '(state: IDownloadState, { payload }: Action<ITrack[]>) => { tracks: ITrack[]

**Comment by yuche** [comment]
`quick build` 问题是没有影响的。参考:https://github.com/yuche/gouqi/issues/6
我建议你看一下三楼提供的链接 https://github.com/yuche/gouqi/issues/7#issuecomment-308130085
应该是 `watchman` 的问题

**Comment by TheWaWaR** [comment]
@lionheart2016 
大致原因就是你的 `watchman` 要重新装一下。

有两种方式你都可以试试：
### 方法1
``` bash
brew uninstall watchman
brew link automake
brew install --HEAD watchman
```
### 方法2
`rm -rf /usr/local/var/run/watchman/ && brew uninstall watchman && brew install watchman`
